version: '3.9'
services:
  db:
    image: couchdb:latest 
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=4455
    restart: always
    volumes:
        - ./dbdata:/opt/couchdb/data
        - /var/lib/couchdb/:/var/lib/couchdb/
  nodeapp:
    restart: always
    build:
      context: ./expressapp/
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    stdin_open: true
    volumes:
      - ./expressapp:/code/expressapp/
      - /code/expressapp/node_modules
    depends_on:
      - db
 
